# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
from ._swig_wrap import _emit_swig_array

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _emit_swig_array.delete_SwigPyIterator

    def value(self):
        return _emit_swig_array.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _emit_swig_array.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _emit_swig_array.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _emit_swig_array.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _emit_swig_array.SwigPyIterator_equal(self, x)

    def copy(self):
        return _emit_swig_array.SwigPyIterator_copy(self)

    def next(self):
        return _emit_swig_array.SwigPyIterator_next(self)

    def __next__(self):
        return _emit_swig_array.SwigPyIterator___next__(self)

    def previous(self):
        return _emit_swig_array.SwigPyIterator_previous(self)

    def advance(self, n):
        return _emit_swig_array.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _emit_swig_array.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _emit_swig_array.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _emit_swig_array.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _emit_swig_array.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _emit_swig_array.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _emit_swig_array.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _emit_swig_array:
_emit_swig_array.SwigPyIterator_swigregister(SwigPyIterator)

def cdata(ptr, nelements=1):
    return _emit_swig_array.cdata(ptr, nelements)

def memmove(data, indata):
    return _emit_swig_array.memmove(data, indata)
fromStart = _emit_swig_array.fromStart
toEnd = _emit_swig_array.toEnd
class Range(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.Range_swiginit(self, _emit_swig_array.new_Range(*args))

    def first(self, lowRange=0):
        return _emit_swig_array.Range_first(self, lowRange)

    def last(self, highRange=0):
        return _emit_swig_array.Range_last(self, highRange)

    def length(self, arg2=0):
        return _emit_swig_array.Range_length(self, arg2)

    def stride(self):
        return _emit_swig_array.Range_stride(self)

    def isAscendingContiguous(self):
        return _emit_swig_array.Range_isAscendingContiguous(self)

    def setRange(self, first, last, stride=1):
        return _emit_swig_array.Range_setRange(self, first, last, stride)

    @staticmethod
    def all():
        return _emit_swig_array.Range_all()

    def isUnitStride(self):
        return _emit_swig_array.Range_isUnitStride(self)
    __swig_destroy__ = _emit_swig_array.delete_Range

# Register Range in _emit_swig_array:
_emit_swig_array.Range_swigregister(Range)
class BlitzArray_double_1(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_double_1_swiginit(self, _emit_swig_array.new_BlitzArray_double_1(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_double_1_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_double_1_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_double_1_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_double_1_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_double_1_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_double_1_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_double_1_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_double_1_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_double_1_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_double_1

# Register BlitzArray_double_1 in _emit_swig_array:
_emit_swig_array.BlitzArray_double_1_swigregister(BlitzArray_double_1)
class BlitzArray_double_2(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_double_2_swiginit(self, _emit_swig_array.new_BlitzArray_double_2(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_double_2_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_double_2_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_double_2_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_double_2_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_double_2_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_double_2_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_double_2_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_double_2_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_double_2_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_double_2

# Register BlitzArray_double_2 in _emit_swig_array:
_emit_swig_array.BlitzArray_double_2_swigregister(BlitzArray_double_2)
class BlitzArray_double_3(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_double_3_swiginit(self, _emit_swig_array.new_BlitzArray_double_3(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_double_3_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_double_3_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_double_3_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_double_3_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_double_3_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_double_3_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_double_3_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_double_3_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_double_3_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_double_3

# Register BlitzArray_double_3 in _emit_swig_array:
_emit_swig_array.BlitzArray_double_3_swigregister(BlitzArray_double_3)
class BlitzArray_double_4(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_double_4_swiginit(self, _emit_swig_array.new_BlitzArray_double_4(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_double_4_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_double_4_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_double_4_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_double_4_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_double_4_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_double_4_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_double_4_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_double_4_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_double_4_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_double_4

# Register BlitzArray_double_4 in _emit_swig_array:
_emit_swig_array.BlitzArray_double_4_swigregister(BlitzArray_double_4)
class BlitzArray_double_5(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_double_5_swiginit(self, _emit_swig_array.new_BlitzArray_double_5(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_double_5_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_double_5_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_double_5_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_double_5_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_double_5_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_double_5_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_double_5_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_double_5_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_double_5_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_double_5

# Register BlitzArray_double_5 in _emit_swig_array:
_emit_swig_array.BlitzArray_double_5_swigregister(BlitzArray_double_5)
class BlitzArray_double_6(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_double_6_swiginit(self, _emit_swig_array.new_BlitzArray_double_6(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_double_6_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_double_6_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_double_6_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_double_6_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_double_6_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_double_6_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_double_6_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_double_6_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_double_6_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_double_6

# Register BlitzArray_double_6 in _emit_swig_array:
_emit_swig_array.BlitzArray_double_6_swigregister(BlitzArray_double_6)
class BlitzArray_double_7(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_double_7_swiginit(self, _emit_swig_array.new_BlitzArray_double_7(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_double_7_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_double_7_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_double_7_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_double_7_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_double_7_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_double_7_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_double_7_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_double_7_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_double_7_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_double_7

# Register BlitzArray_double_7 in _emit_swig_array:
_emit_swig_array.BlitzArray_double_7_swigregister(BlitzArray_double_7)
class BlitzArray_double_8(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_double_8_swiginit(self, _emit_swig_array.new_BlitzArray_double_8(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_double_8_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_double_8_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_double_8_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_double_8_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_double_8_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_double_8_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_double_8_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_double_8_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_double_8_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_double_8

# Register BlitzArray_double_8 in _emit_swig_array:
_emit_swig_array.BlitzArray_double_8_swigregister(BlitzArray_double_8)
class BlitzArray_bool_1(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_bool_1_swiginit(self, _emit_swig_array.new_BlitzArray_bool_1(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_bool_1_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_bool_1_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_bool_1_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_bool_1_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_bool_1_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_bool_1_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_bool_1_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_bool_1_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_bool_1_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_bool_1

# Register BlitzArray_bool_1 in _emit_swig_array:
_emit_swig_array.BlitzArray_bool_1_swigregister(BlitzArray_bool_1)
class BlitzArray_bool_2(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_bool_2_swiginit(self, _emit_swig_array.new_BlitzArray_bool_2(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_bool_2_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_bool_2_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_bool_2_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_bool_2_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_bool_2_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_bool_2_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_bool_2_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_bool_2_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_bool_2_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_bool_2

# Register BlitzArray_bool_2 in _emit_swig_array:
_emit_swig_array.BlitzArray_bool_2_swigregister(BlitzArray_bool_2)
class BlitzArray_bool_3(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_bool_3_swiginit(self, _emit_swig_array.new_BlitzArray_bool_3(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_bool_3_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_bool_3_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_bool_3_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_bool_3_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_bool_3_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_bool_3_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_bool_3_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_bool_3_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_bool_3_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_bool_3

# Register BlitzArray_bool_3 in _emit_swig_array:
_emit_swig_array.BlitzArray_bool_3_swigregister(BlitzArray_bool_3)
class BlitzArray_bool_4(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_bool_4_swiginit(self, _emit_swig_array.new_BlitzArray_bool_4(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_bool_4_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_bool_4_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_bool_4_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_bool_4_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_bool_4_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_bool_4_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_bool_4_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_bool_4_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_bool_4_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_bool_4

# Register BlitzArray_bool_4 in _emit_swig_array:
_emit_swig_array.BlitzArray_bool_4_swigregister(BlitzArray_bool_4)
class BlitzArray_bool_5(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_bool_5_swiginit(self, _emit_swig_array.new_BlitzArray_bool_5(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_bool_5_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_bool_5_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_bool_5_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_bool_5_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_bool_5_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_bool_5_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_bool_5_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_bool_5_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_bool_5_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_bool_5

# Register BlitzArray_bool_5 in _emit_swig_array:
_emit_swig_array.BlitzArray_bool_5_swigregister(BlitzArray_bool_5)
class BlitzArray_bool_6(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_bool_6_swiginit(self, _emit_swig_array.new_BlitzArray_bool_6(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_bool_6_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_bool_6_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_bool_6_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_bool_6_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_bool_6_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_bool_6_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_bool_6_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_bool_6_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_bool_6_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_bool_6

# Register BlitzArray_bool_6 in _emit_swig_array:
_emit_swig_array.BlitzArray_bool_6_swigregister(BlitzArray_bool_6)
class BlitzArray_bool_7(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_bool_7_swiginit(self, _emit_swig_array.new_BlitzArray_bool_7(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_bool_7_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_bool_7_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_bool_7_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_bool_7_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_bool_7_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_bool_7_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_bool_7_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_bool_7_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_bool_7_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_bool_7

# Register BlitzArray_bool_7 in _emit_swig_array:
_emit_swig_array.BlitzArray_bool_7_swigregister(BlitzArray_bool_7)
class BlitzArray_bool_8(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_bool_8_swiginit(self, _emit_swig_array.new_BlitzArray_bool_8(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_bool_8_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_bool_8_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_bool_8_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_bool_8_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_bool_8_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_bool_8_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_bool_8_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_bool_8_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_bool_8_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_bool_8

# Register BlitzArray_bool_8 in _emit_swig_array:
_emit_swig_array.BlitzArray_bool_8_swigregister(BlitzArray_bool_8)
class BlitzArray_int_1(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_int_1_swiginit(self, _emit_swig_array.new_BlitzArray_int_1(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_int_1_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_int_1_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_int_1_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_int_1_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_int_1_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_int_1_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_int_1_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_int_1_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_int_1_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_int_1

# Register BlitzArray_int_1 in _emit_swig_array:
_emit_swig_array.BlitzArray_int_1_swigregister(BlitzArray_int_1)
class BlitzArray_int_2(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_int_2_swiginit(self, _emit_swig_array.new_BlitzArray_int_2(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_int_2_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_int_2_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_int_2_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_int_2_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_int_2_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_int_2_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_int_2_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_int_2_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_int_2_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_int_2

# Register BlitzArray_int_2 in _emit_swig_array:
_emit_swig_array.BlitzArray_int_2_swigregister(BlitzArray_int_2)
class BlitzArray_int_3(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_int_3_swiginit(self, _emit_swig_array.new_BlitzArray_int_3(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_int_3_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_int_3_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_int_3_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_int_3_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_int_3_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_int_3_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_int_3_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_int_3_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_int_3_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_int_3

# Register BlitzArray_int_3 in _emit_swig_array:
_emit_swig_array.BlitzArray_int_3_swigregister(BlitzArray_int_3)
class BlitzArray_int_4(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_int_4_swiginit(self, _emit_swig_array.new_BlitzArray_int_4(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_int_4_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_int_4_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_int_4_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_int_4_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_int_4_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_int_4_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_int_4_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_int_4_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_int_4_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_int_4

# Register BlitzArray_int_4 in _emit_swig_array:
_emit_swig_array.BlitzArray_int_4_swigregister(BlitzArray_int_4)
class BlitzArray_int_5(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_int_5_swiginit(self, _emit_swig_array.new_BlitzArray_int_5(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_int_5_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_int_5_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_int_5_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_int_5_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_int_5_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_int_5_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_int_5_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_int_5_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_int_5_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_int_5

# Register BlitzArray_int_5 in _emit_swig_array:
_emit_swig_array.BlitzArray_int_5_swigregister(BlitzArray_int_5)
class BlitzArray_int_6(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_int_6_swiginit(self, _emit_swig_array.new_BlitzArray_int_6(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_int_6_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_int_6_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_int_6_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_int_6_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_int_6_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_int_6_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_int_6_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_int_6_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_int_6_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_int_6

# Register BlitzArray_int_6 in _emit_swig_array:
_emit_swig_array.BlitzArray_int_6_swigregister(BlitzArray_int_6)
class BlitzArray_int_7(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_int_7_swiginit(self, _emit_swig_array.new_BlitzArray_int_7(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_int_7_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_int_7_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_int_7_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_int_7_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_int_7_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_int_7_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_int_7_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_int_7_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_int_7_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_int_7

# Register BlitzArray_int_7 in _emit_swig_array:
_emit_swig_array.BlitzArray_int_7_swigregister(BlitzArray_int_7)
class BlitzArray_int_8(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_int_8_swiginit(self, _emit_swig_array.new_BlitzArray_int_8(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_int_8_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_int_8_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_int_8_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_int_8_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_int_8_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_int_8_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_int_8_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_int_8_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_int_8_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_int_8

# Register BlitzArray_int_8 in _emit_swig_array:
_emit_swig_array.BlitzArray_int_8_swigregister(BlitzArray_int_8)
class BlitzArray_uint_1(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_uint_1_swiginit(self, _emit_swig_array.new_BlitzArray_uint_1(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_uint_1_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_uint_1_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_uint_1_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_uint_1_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_uint_1_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_uint_1_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_uint_1_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_uint_1_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_uint_1_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_uint_1

# Register BlitzArray_uint_1 in _emit_swig_array:
_emit_swig_array.BlitzArray_uint_1_swigregister(BlitzArray_uint_1)
class BlitzArray_uint_2(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_uint_2_swiginit(self, _emit_swig_array.new_BlitzArray_uint_2(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_uint_2_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_uint_2_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_uint_2_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_uint_2_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_uint_2_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_uint_2_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_uint_2_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_uint_2_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_uint_2_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_uint_2

# Register BlitzArray_uint_2 in _emit_swig_array:
_emit_swig_array.BlitzArray_uint_2_swigregister(BlitzArray_uint_2)
class BlitzArray_uint_3(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_uint_3_swiginit(self, _emit_swig_array.new_BlitzArray_uint_3(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_uint_3_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_uint_3_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_uint_3_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_uint_3_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_uint_3_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_uint_3_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_uint_3_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_uint_3_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_uint_3_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_uint_3

# Register BlitzArray_uint_3 in _emit_swig_array:
_emit_swig_array.BlitzArray_uint_3_swigregister(BlitzArray_uint_3)
class BlitzArray_uint_4(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_uint_4_swiginit(self, _emit_swig_array.new_BlitzArray_uint_4(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_uint_4_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_uint_4_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_uint_4_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_uint_4_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_uint_4_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_uint_4_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_uint_4_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_uint_4_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_uint_4_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_uint_4

# Register BlitzArray_uint_4 in _emit_swig_array:
_emit_swig_array.BlitzArray_uint_4_swigregister(BlitzArray_uint_4)
class BlitzArray_uint_5(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_uint_5_swiginit(self, _emit_swig_array.new_BlitzArray_uint_5(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_uint_5_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_uint_5_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_uint_5_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_uint_5_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_uint_5_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_uint_5_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_uint_5_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_uint_5_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_uint_5_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_uint_5

# Register BlitzArray_uint_5 in _emit_swig_array:
_emit_swig_array.BlitzArray_uint_5_swigregister(BlitzArray_uint_5)
class BlitzArray_uint_6(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_uint_6_swiginit(self, _emit_swig_array.new_BlitzArray_uint_6(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_uint_6_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_uint_6_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_uint_6_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_uint_6_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_uint_6_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_uint_6_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_uint_6_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_uint_6_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_uint_6_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_uint_6

# Register BlitzArray_uint_6 in _emit_swig_array:
_emit_swig_array.BlitzArray_uint_6_swigregister(BlitzArray_uint_6)
class BlitzArray_uint_7(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_uint_7_swiginit(self, _emit_swig_array.new_BlitzArray_uint_7(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_uint_7_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_uint_7_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_uint_7_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_uint_7_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_uint_7_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_uint_7_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_uint_7_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_uint_7_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_uint_7_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_uint_7

# Register BlitzArray_uint_7 in _emit_swig_array:
_emit_swig_array.BlitzArray_uint_7_swigregister(BlitzArray_uint_7)
class BlitzArray_uint_8(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_uint_8_swiginit(self, _emit_swig_array.new_BlitzArray_uint_8(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_uint_8_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_uint_8_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_uint_8_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_uint_8_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_uint_8_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_uint_8_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_uint_8_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_uint_8_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_uint_8_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_uint_8

# Register BlitzArray_uint_8 in _emit_swig_array:
_emit_swig_array.BlitzArray_uint_8_swigregister(BlitzArray_uint_8)
class BlitzArray_float_1(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_float_1_swiginit(self, _emit_swig_array.new_BlitzArray_float_1(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_float_1_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_float_1_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_float_1_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_float_1_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_float_1_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_float_1_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_float_1_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_float_1_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_float_1_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_float_1

# Register BlitzArray_float_1 in _emit_swig_array:
_emit_swig_array.BlitzArray_float_1_swigregister(BlitzArray_float_1)
class BlitzArray_float_2(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_float_2_swiginit(self, _emit_swig_array.new_BlitzArray_float_2(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_float_2_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_float_2_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_float_2_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_float_2_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_float_2_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_float_2_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_float_2_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_float_2_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_float_2_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_float_2

# Register BlitzArray_float_2 in _emit_swig_array:
_emit_swig_array.BlitzArray_float_2_swigregister(BlitzArray_float_2)
class BlitzArray_float_3(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_float_3_swiginit(self, _emit_swig_array.new_BlitzArray_float_3(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_float_3_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_float_3_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_float_3_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_float_3_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_float_3_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_float_3_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_float_3_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_float_3_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_float_3_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_float_3

# Register BlitzArray_float_3 in _emit_swig_array:
_emit_swig_array.BlitzArray_float_3_swigregister(BlitzArray_float_3)
class BlitzArray_float_4(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_float_4_swiginit(self, _emit_swig_array.new_BlitzArray_float_4(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_float_4_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_float_4_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_float_4_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_float_4_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_float_4_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_float_4_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_float_4_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_float_4_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_float_4_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_float_4

# Register BlitzArray_float_4 in _emit_swig_array:
_emit_swig_array.BlitzArray_float_4_swigregister(BlitzArray_float_4)
class BlitzArray_float_5(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_float_5_swiginit(self, _emit_swig_array.new_BlitzArray_float_5(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_float_5_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_float_5_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_float_5_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_float_5_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_float_5_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_float_5_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_float_5_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_float_5_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_float_5_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_float_5

# Register BlitzArray_float_5 in _emit_swig_array:
_emit_swig_array.BlitzArray_float_5_swigregister(BlitzArray_float_5)
class BlitzArray_float_6(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_float_6_swiginit(self, _emit_swig_array.new_BlitzArray_float_6(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_float_6_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_float_6_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_float_6_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_float_6_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_float_6_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_float_6_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_float_6_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_float_6_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_float_6_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_float_6

# Register BlitzArray_float_6 in _emit_swig_array:
_emit_swig_array.BlitzArray_float_6_swigregister(BlitzArray_float_6)
class BlitzArray_float_7(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_float_7_swiginit(self, _emit_swig_array.new_BlitzArray_float_7(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_float_7_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_float_7_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_float_7_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_float_7_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_float_7_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_float_7_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_float_7_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_float_7_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_float_7_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_float_7

# Register BlitzArray_float_7 in _emit_swig_array:
_emit_swig_array.BlitzArray_float_7_swigregister(BlitzArray_float_7)
class BlitzArray_float_8(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_float_8_swiginit(self, _emit_swig_array.new_BlitzArray_float_8(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_float_8_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_float_8_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_float_8_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_float_8_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_float_8_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_float_8_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_float_8_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_float_8_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_float_8_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_float_8

# Register BlitzArray_float_8 in _emit_swig_array:
_emit_swig_array.BlitzArray_float_8_swigregister(BlitzArray_float_8)
class BlitzArray_short_1(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_short_1_swiginit(self, _emit_swig_array.new_BlitzArray_short_1(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_short_1_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_short_1_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_short_1_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_short_1_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_short_1_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_short_1_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_short_1_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_short_1_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_short_1_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_short_1

# Register BlitzArray_short_1 in _emit_swig_array:
_emit_swig_array.BlitzArray_short_1_swigregister(BlitzArray_short_1)
class BlitzArray_short_2(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_short_2_swiginit(self, _emit_swig_array.new_BlitzArray_short_2(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_short_2_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_short_2_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_short_2_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_short_2_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_short_2_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_short_2_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_short_2_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_short_2_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_short_2_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_short_2

# Register BlitzArray_short_2 in _emit_swig_array:
_emit_swig_array.BlitzArray_short_2_swigregister(BlitzArray_short_2)
class BlitzArray_short_3(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_short_3_swiginit(self, _emit_swig_array.new_BlitzArray_short_3(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_short_3_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_short_3_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_short_3_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_short_3_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_short_3_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_short_3_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_short_3_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_short_3_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_short_3_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_short_3

# Register BlitzArray_short_3 in _emit_swig_array:
_emit_swig_array.BlitzArray_short_3_swigregister(BlitzArray_short_3)
class BlitzArray_short_4(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_short_4_swiginit(self, _emit_swig_array.new_BlitzArray_short_4(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_short_4_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_short_4_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_short_4_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_short_4_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_short_4_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_short_4_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_short_4_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_short_4_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_short_4_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_short_4

# Register BlitzArray_short_4 in _emit_swig_array:
_emit_swig_array.BlitzArray_short_4_swigregister(BlitzArray_short_4)
class BlitzArray_short_5(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_short_5_swiginit(self, _emit_swig_array.new_BlitzArray_short_5(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_short_5_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_short_5_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_short_5_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_short_5_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_short_5_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_short_5_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_short_5_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_short_5_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_short_5_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_short_5

# Register BlitzArray_short_5 in _emit_swig_array:
_emit_swig_array.BlitzArray_short_5_swigregister(BlitzArray_short_5)
class BlitzArray_short_6(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_short_6_swiginit(self, _emit_swig_array.new_BlitzArray_short_6(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_short_6_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_short_6_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_short_6_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_short_6_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_short_6_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_short_6_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_short_6_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_short_6_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_short_6_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_short_6

# Register BlitzArray_short_6 in _emit_swig_array:
_emit_swig_array.BlitzArray_short_6_swigregister(BlitzArray_short_6)
class BlitzArray_short_7(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_short_7_swiginit(self, _emit_swig_array.new_BlitzArray_short_7(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_short_7_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_short_7_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_short_7_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_short_7_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_short_7_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_short_7_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_short_7_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_short_7_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_short_7_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_short_7

# Register BlitzArray_short_7 in _emit_swig_array:
_emit_swig_array.BlitzArray_short_7_swigregister(BlitzArray_short_7)
class BlitzArray_short_8(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_short_8_swiginit(self, _emit_swig_array.new_BlitzArray_short_8(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_short_8_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_short_8_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_short_8_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_short_8_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_short_8_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_short_8_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_short_8_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_short_8_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_short_8_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_short_8

# Register BlitzArray_short_8 in _emit_swig_array:
_emit_swig_array.BlitzArray_short_8_swigregister(BlitzArray_short_8)
class BlitzArray_ushort_1(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_ushort_1_swiginit(self, _emit_swig_array.new_BlitzArray_ushort_1(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_ushort_1_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_ushort_1_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_ushort_1_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_ushort_1_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_ushort_1_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_ushort_1_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_ushort_1_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_ushort_1_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_ushort_1_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_ushort_1

# Register BlitzArray_ushort_1 in _emit_swig_array:
_emit_swig_array.BlitzArray_ushort_1_swigregister(BlitzArray_ushort_1)
class BlitzArray_ushort_2(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_ushort_2_swiginit(self, _emit_swig_array.new_BlitzArray_ushort_2(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_ushort_2_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_ushort_2_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_ushort_2_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_ushort_2_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_ushort_2_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_ushort_2_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_ushort_2_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_ushort_2_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_ushort_2_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_ushort_2

# Register BlitzArray_ushort_2 in _emit_swig_array:
_emit_swig_array.BlitzArray_ushort_2_swigregister(BlitzArray_ushort_2)
class BlitzArray_ushort_3(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_ushort_3_swiginit(self, _emit_swig_array.new_BlitzArray_ushort_3(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_ushort_3_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_ushort_3_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_ushort_3_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_ushort_3_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_ushort_3_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_ushort_3_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_ushort_3_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_ushort_3_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_ushort_3_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_ushort_3

# Register BlitzArray_ushort_3 in _emit_swig_array:
_emit_swig_array.BlitzArray_ushort_3_swigregister(BlitzArray_ushort_3)
class BlitzArray_ushort_4(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_ushort_4_swiginit(self, _emit_swig_array.new_BlitzArray_ushort_4(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_ushort_4_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_ushort_4_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_ushort_4_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_ushort_4_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_ushort_4_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_ushort_4_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_ushort_4_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_ushort_4_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_ushort_4_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_ushort_4

# Register BlitzArray_ushort_4 in _emit_swig_array:
_emit_swig_array.BlitzArray_ushort_4_swigregister(BlitzArray_ushort_4)
class BlitzArray_ushort_5(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_ushort_5_swiginit(self, _emit_swig_array.new_BlitzArray_ushort_5(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_ushort_5_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_ushort_5_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_ushort_5_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_ushort_5_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_ushort_5_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_ushort_5_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_ushort_5_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_ushort_5_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_ushort_5_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_ushort_5

# Register BlitzArray_ushort_5 in _emit_swig_array:
_emit_swig_array.BlitzArray_ushort_5_swigregister(BlitzArray_ushort_5)
class BlitzArray_ushort_6(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_ushort_6_swiginit(self, _emit_swig_array.new_BlitzArray_ushort_6(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_ushort_6_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_ushort_6_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_ushort_6_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_ushort_6_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_ushort_6_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_ushort_6_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_ushort_6_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_ushort_6_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_ushort_6_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_ushort_6

# Register BlitzArray_ushort_6 in _emit_swig_array:
_emit_swig_array.BlitzArray_ushort_6_swigregister(BlitzArray_ushort_6)
class BlitzArray_ushort_7(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_ushort_7_swiginit(self, _emit_swig_array.new_BlitzArray_ushort_7(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_ushort_7_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_ushort_7_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_ushort_7_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_ushort_7_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_ushort_7_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_ushort_7_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_ushort_7_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_ushort_7_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_ushort_7_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_ushort_7

# Register BlitzArray_ushort_7 in _emit_swig_array:
_emit_swig_array.BlitzArray_ushort_7_swigregister(BlitzArray_ushort_7)
class BlitzArray_ushort_8(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_ushort_8_swiginit(self, _emit_swig_array.new_BlitzArray_ushort_8(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_ushort_8_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_ushort_8_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_ushort_8_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_ushort_8_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_ushort_8_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_ushort_8_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_ushort_8_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_ushort_8_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_ushort_8_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_ushort_8

# Register BlitzArray_ushort_8 in _emit_swig_array:
_emit_swig_array.BlitzArray_ushort_8_swigregister(BlitzArray_ushort_8)
class BlitzArray_char_1(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_char_1_swiginit(self, _emit_swig_array.new_BlitzArray_char_1(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_char_1_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_char_1_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_char_1_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_char_1_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_char_1_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_char_1_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_char_1_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_char_1_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_char_1_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_char_1

# Register BlitzArray_char_1 in _emit_swig_array:
_emit_swig_array.BlitzArray_char_1_swigregister(BlitzArray_char_1)
class BlitzArray_char_2(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_char_2_swiginit(self, _emit_swig_array.new_BlitzArray_char_2(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_char_2_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_char_2_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_char_2_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_char_2_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_char_2_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_char_2_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_char_2_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_char_2_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_char_2_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_char_2

# Register BlitzArray_char_2 in _emit_swig_array:
_emit_swig_array.BlitzArray_char_2_swigregister(BlitzArray_char_2)
class BlitzArray_char_3(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_char_3_swiginit(self, _emit_swig_array.new_BlitzArray_char_3(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_char_3_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_char_3_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_char_3_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_char_3_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_char_3_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_char_3_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_char_3_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_char_3_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_char_3_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_char_3

# Register BlitzArray_char_3 in _emit_swig_array:
_emit_swig_array.BlitzArray_char_3_swigregister(BlitzArray_char_3)
class BlitzArray_char_4(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_char_4_swiginit(self, _emit_swig_array.new_BlitzArray_char_4(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_char_4_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_char_4_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_char_4_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_char_4_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_char_4_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_char_4_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_char_4_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_char_4_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_char_4_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_char_4

# Register BlitzArray_char_4 in _emit_swig_array:
_emit_swig_array.BlitzArray_char_4_swigregister(BlitzArray_char_4)
class BlitzArray_char_5(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_char_5_swiginit(self, _emit_swig_array.new_BlitzArray_char_5(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_char_5_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_char_5_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_char_5_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_char_5_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_char_5_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_char_5_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_char_5_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_char_5_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_char_5_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_char_5

# Register BlitzArray_char_5 in _emit_swig_array:
_emit_swig_array.BlitzArray_char_5_swigregister(BlitzArray_char_5)
class BlitzArray_char_6(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_char_6_swiginit(self, _emit_swig_array.new_BlitzArray_char_6(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_char_6_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_char_6_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_char_6_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_char_6_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_char_6_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_char_6_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_char_6_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_char_6_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_char_6_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_char_6

# Register BlitzArray_char_6 in _emit_swig_array:
_emit_swig_array.BlitzArray_char_6_swigregister(BlitzArray_char_6)
class BlitzArray_char_7(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_char_7_swiginit(self, _emit_swig_array.new_BlitzArray_char_7(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_char_7_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_char_7_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_char_7_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_char_7_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_char_7_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_char_7_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_char_7_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_char_7_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_char_7_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_char_7

# Register BlitzArray_char_7 in _emit_swig_array:
_emit_swig_array.BlitzArray_char_7_swigregister(BlitzArray_char_7)
class BlitzArray_char_8(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_char_8_swiginit(self, _emit_swig_array.new_BlitzArray_char_8(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_char_8_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_char_8_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_char_8_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_char_8_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_char_8_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_char_8_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_char_8_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_char_8_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_char_8_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_char_8

# Register BlitzArray_char_8 in _emit_swig_array:
_emit_swig_array.BlitzArray_char_8_swigregister(BlitzArray_char_8)
class BlitzArray_uchar_1(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_uchar_1_swiginit(self, _emit_swig_array.new_BlitzArray_uchar_1(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_uchar_1_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_uchar_1_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_uchar_1_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_uchar_1_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_uchar_1_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_uchar_1_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_uchar_1_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_uchar_1_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_uchar_1_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_uchar_1

# Register BlitzArray_uchar_1 in _emit_swig_array:
_emit_swig_array.BlitzArray_uchar_1_swigregister(BlitzArray_uchar_1)
class BlitzArray_uchar_2(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_uchar_2_swiginit(self, _emit_swig_array.new_BlitzArray_uchar_2(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_uchar_2_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_uchar_2_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_uchar_2_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_uchar_2_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_uchar_2_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_uchar_2_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_uchar_2_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_uchar_2_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_uchar_2_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_uchar_2

# Register BlitzArray_uchar_2 in _emit_swig_array:
_emit_swig_array.BlitzArray_uchar_2_swigregister(BlitzArray_uchar_2)
class BlitzArray_uchar_3(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_uchar_3_swiginit(self, _emit_swig_array.new_BlitzArray_uchar_3(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_uchar_3_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_uchar_3_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_uchar_3_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_uchar_3_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_uchar_3_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_uchar_3_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_uchar_3_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_uchar_3_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_uchar_3_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_uchar_3

# Register BlitzArray_uchar_3 in _emit_swig_array:
_emit_swig_array.BlitzArray_uchar_3_swigregister(BlitzArray_uchar_3)
class BlitzArray_uchar_4(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_uchar_4_swiginit(self, _emit_swig_array.new_BlitzArray_uchar_4(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_uchar_4_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_uchar_4_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_uchar_4_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_uchar_4_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_uchar_4_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_uchar_4_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_uchar_4_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_uchar_4_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_uchar_4_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_uchar_4

# Register BlitzArray_uchar_4 in _emit_swig_array:
_emit_swig_array.BlitzArray_uchar_4_swigregister(BlitzArray_uchar_4)
class BlitzArray_uchar_5(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_uchar_5_swiginit(self, _emit_swig_array.new_BlitzArray_uchar_5(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_uchar_5_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_uchar_5_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_uchar_5_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_uchar_5_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_uchar_5_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_uchar_5_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_uchar_5_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_uchar_5_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_uchar_5_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_uchar_5

# Register BlitzArray_uchar_5 in _emit_swig_array:
_emit_swig_array.BlitzArray_uchar_5_swigregister(BlitzArray_uchar_5)
class BlitzArray_uchar_6(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_uchar_6_swiginit(self, _emit_swig_array.new_BlitzArray_uchar_6(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_uchar_6_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_uchar_6_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_uchar_6_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_uchar_6_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_uchar_6_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_uchar_6_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_uchar_6_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_uchar_6_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_uchar_6_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_uchar_6

# Register BlitzArray_uchar_6 in _emit_swig_array:
_emit_swig_array.BlitzArray_uchar_6_swigregister(BlitzArray_uchar_6)
class BlitzArray_uchar_7(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_uchar_7_swiginit(self, _emit_swig_array.new_BlitzArray_uchar_7(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_uchar_7_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_uchar_7_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_uchar_7_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_uchar_7_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_uchar_7_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_uchar_7_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_uchar_7_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_uchar_7_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_uchar_7_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_uchar_7

# Register BlitzArray_uchar_7 in _emit_swig_array:
_emit_swig_array.BlitzArray_uchar_7_swigregister(BlitzArray_uchar_7)
class BlitzArray_uchar_8(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _emit_swig_array.BlitzArray_uchar_8_swiginit(self, _emit_swig_array.new_BlitzArray_uchar_8(*args))

    def data(self):
        return _emit_swig_array.BlitzArray_uchar_8_data(self)

    def size(self):
        return _emit_swig_array.BlitzArray_uchar_8_size(self)

    def read(self, *args):
        return _emit_swig_array.BlitzArray_uchar_8_read(self, *args)

    def write(self, *args):
        return _emit_swig_array.BlitzArray_uchar_8_write(self, *args)

    def datav(self):
        return _emit_swig_array.BlitzArray_uchar_8_datav(self)

    def shape0(self):
        return _emit_swig_array.BlitzArray_uchar_8_shape0(self)

    def shape1(self):
        return _emit_swig_array.BlitzArray_uchar_8_shape1(self)

    def shape2(self):
        return _emit_swig_array.BlitzArray_uchar_8_shape2(self)

    def shape3(self):
        return _emit_swig_array.BlitzArray_uchar_8_shape3(self)
    __swig_destroy__ = _emit_swig_array.delete_BlitzArray_uchar_8

# Register BlitzArray_uchar_8 in _emit_swig_array:
_emit_swig_array.BlitzArray_uchar_8_swigregister(BlitzArray_uchar_8)

__all__ = []  
for t in ("double", "bool", "int", "uint", "float", "short", "ushort", "char", "uchar"):
    for d in range(1,8+1):
        __all__.append("BlitzArray_%s_%d" % (t, d))


